
// ============================================================
// TRANSLATIONS
// ============================================================
const i18n = {
  fr: {
    'nav.home': 'Accueil',
    'nav.tours': 'City Tours ▾',
    'nav.tour.nice': 'Nice : City Tour',
    'nav.tour.riviera': 'French Riviera City Tour',
    'nav.tour.night': 'Nice by Night',
    'nav.events': 'Évènements',
    'nav.reviews': 'Avis',
    'nav.contact': 'Contact',
    'nav.book': 'Réserver',
    'hero.eyebrow': 'Nice · Monaco · Côte d\'Azur',
    'hero.script': 'l\'échappée belle',
    'hero.sub': 'Une expérience authentique et inoubliable à bord de side-cars vintage, entre mer turquoise, villages perchés et lumière du Sud.',
    'hero.book': 'Réserver ma balade',
    'hero.discover': 'Découvrir les tours',
    'hero.scroll': 'Scroll',
    'intro.eyebrow': 'L\'échappée belle',
    'intro.title': 'Plongez dans l\'âme de la <em>Côte d\'Azur</em>',
    'intro.p1': 'Venez visiter Nice et la French Riviera à bord de nos side-cars ! Laissez-vous conduire par un chauffeur expérimenté et profitez de la beauté des paysages.',
    'intro.p2': 'Nos balades en side-car sont bien plus qu\'une simple visite touristique : c\'est une plongée dans l\'âme de la Côte d\'Azur, un voyage dans le temps et l\'espace qui éveille tous les sens. Entre mer et montagne, villages médiévaux et stations balnéaires chics, chaque étape est une nouvelle découverte.',
    'intro.p3': 'Montez à bord, laissez-vous rythmer par le ronronnement du moteur, le vent marin dans vos cheveux, et admirez le charme de la Riviera pour des souvenirs impérissables.',
    'intro.stamp.since': 'Depuis',
    'tours.eyebrow': 'Nos itinéraires signature',
    'tours.title': 'Trois <em>balades</em> pour vivre la Riviera',
    'tours.lead': 'De Nice à Monaco, de la Promenade des Anglais aux villages perchés, chaque tour est pensé pour révéler la magie de la Côte d\'Azur.',
    'tours.more': 'Plus d\'infos',
    'tours.night': 'Nuit',
    'tour1.title': 'Nice City Tour',
    'tour1.desc': 'Visitez les lieux incontournables de Nissa la Bella : Place Masséna, Port de Nice, Mont-Boron, Villefranche-sur-Mer et son célèbre plongeoir de La Réserve.',
    'tour2.title': 'French Riviera',
    'tour2.desc': 'L\'itinéraire complet de la Côte d\'Azur : Beaulieu-sur-Mer, Cap d\'Ail, Monaco, le circuit de F1, la Grande Corniche, La Turbie et Èze, village médiéval perché.',
    'tour3.title': 'Nice by Night',
    'tour3.desc': 'Nice se métamorphose à la nuit tombée. Flânez le long de la Promenade des Anglais illuminée, la douce brise marine et les lumières qui se reflètent sur la mer. Magie assurée.',
    'exp.eyebrow': 'L\'expérience Riviera',
    'exp.title': 'Cinq promesses, <em>un voyage unique</em>',
    'feat1.title': 'Confort & Sécurité',
    'feat1.desc': 'Un véhicule moderne au style vintage, équipé des dernières technologies en matière de sécurité.',
    'feat2.title': 'Vue Panoramique',
    'feat2.desc': 'Assis dans le panier, vous avez une vue dégagée sur les paysages — idéale pour des photos mémorables.',
    'feat3.title': 'Accès Exclusif',
    'feat3.desc': 'Le side-car se faufile dans les petites rues et les chemins pittoresques inaccessibles aux voitures.',
    'feat4.title': 'Guide Local',
    'feat4.desc': 'Votre chauffeur est un passionné de la région, prêt à partager anecdotes et secrets de la Riviera.',
    'feat5.title': 'Authenticité',
    'feat5.desc': 'Revivez l\'âge d\'or des voyages en side-car — nostalgique, élégant, hors du temps.',
    'events.eyebrow': 'Sur mesure',
    'events.title': 'Pour vos plus <em>beaux jours</em>',
    'events.lead': 'Nous nous adaptons à toutes vos demandes particulières. À l\'écoute de vos envies, nous ferons de notre mieux pour vous satisfaire.',
    'events.item1': 'Mariages & cortèges nuptiaux',
    'events.item2': 'Enterrements de vie de garçon / de jeune fille',
    'events.item3': 'Évènements d\'entreprise & séminaires',
    'events.item4': 'Dégustation de produits locaux avec <a href="https://www.restaurant-lou-bantry.fr/" style="color:var(--gold-2); text-decoration:underline;">Lou Bantry</a>',
    'events.item5': 'Prise en charge au lieu de votre choix (sans supplément sur Nice)',
    'events.cta': 'Nous contacter',
    'press.head': 'Ils parlent de nous',
    'press.quote': 'Une visite rétro « à la française » qui révèle la Riviera sous un angle inattendu et terriblement charmant.',
    'press.article': '« Balades en side-car pour découvrir la Côte d\'Azur autrement »',
    'test.eyebrow': 'Nos clients parlent de nous',
    'test.title': 'Des souvenirs qui <em>durent</em>',
    'test1': '« Superbe balade en side-car vintage ! Une expérience mémorable ! »',
    'test2': '« Une visite magique à bord du sidecar ! Franck est passionné et ça se sent ! »',
    'test3': '« Une expérience inoubliable à travers Nice avec un guide super sympa. »',
    'test1.author': 'Voyageur GetYourGuide',
    'test1.country': 'États-Unis',
    'test2.country': 'Canada',
    'test3.country': 'Italie',
    'contact.title': 'Prêts à embarquer ?',
    'contact.script': 'votre aventure commence ici',
    'contact.lead': 'Réservez votre balade ou contactez-nous pour une demande sur mesure. Nous serons ravis de partager la Riviera avec vous.',
    'contact.book': 'Réserver en ligne',
    'contact.instagram': 'Suivre sur Instagram',
    'footer.brand': 'L\'échappée belle sur la Côte d\'Azur. Balades authentiques en side-car vintage entre Nice, Monaco et la French Riviera.',
    'footer.nav': 'Navigation',
    'footer.nav.tours': 'Nos City Tours',
    'footer.reviews': 'Avis clients',
    'footer.tours.title': 'Nos tours',
    'footer.book': 'Réservation',
    'footer.contact.title': 'Contact',
    'footer.copyright': '© {year} Riviera Sidecar — Tous droits réservés',
    'footer.deco': 'l\'échappée belle',
    'tour.practical': 'Infos pratiques',
    'tour.included': 'Inclus dans la balade',
    'tour.itinerary': 'L\'itinéraire',
    'tour.book.now': 'Réserver maintenant',
    'tour.back': '← Retour aux tours',
    'tour.other.tours': 'Nos autres tours',
    'tour.label.duration': 'Durée',
    'tour.label.depart': 'Départ',
    'tour.label.lang': 'Langues',
    'tour.label.group': 'Groupe',
    'tour.label.avail': 'Disponibilité',
    'tour.avail.year': 'Toute l\'année sur réservation',
    'tour.avail.night': 'Soirées sur réservation',
    'tour.group.value': 'Jusqu\'à 2 passagers',
    'tour.lang.value': 'FR · EN · IT',
    'tour.depart.value': 'Nice Centre (adresse flexible)',
    'tour.inc.helmet': 'Casque & lunettes de protection',
    'tour.inc.guide': 'Guide commentateur passionné',
    'tour.inc.photos': 'Photos souvenir offertes',
    'tour.inc.pickup': 'Prise en charge flexible',
    'tour.inc.insurance': 'Assurance passager incluse',
    'tour.inc.equip': 'Équipement complet fourni',
    'nct.eyebrow': 'Balade vintage · 1h15',
    'nct.script': 'Nissa la Bella',
    'nct.badge': '⏱ 1h15 · Nice & alentours',
    'nct.desc1': 'Explorez les trésors de Nice au rythme du ronronnement d\'un side-car vintage. Votre chauffeur-guide passionné vous emmène à la découverte de Nissa la Bella, de la Promenade des Anglais jusqu\'à la Rade de Villefranche-sur-Mer.',
    'nct.desc2': 'Une heure et quart d\'émerveillement entre mer et collines, de la Vieille Ville médiévale aux panoramas époustouflants du Mont-Boron, jusqu\'au célèbre plongeoir de La Réserve.',
    'nct.stop1': 'Promenade des Anglais',
    'nct.stop2': 'Place Masséna & Vieux-Nice',
    'nct.stop3': 'Port de Nice',
    'nct.stop4': 'Mont-Boron — Panorama sur la Rade',
    'nct.stop5': 'Villefranche-sur-Mer',
    'nct.stop6': 'Plongeoir de La Réserve',
    'nct.book.h2': 'Prêts pour l\'aventure ?',
    'nct.book.script': 'Nice vous attend',
    'nct.book.lead': 'Réservez votre Nice City Tour et vivez la Riviera autrement.',
    'frt.eyebrow': 'Balade signature · 2h30',
    'frt.script': 'De Nice à Monaco',
    'frt.badge': '⏱ 2h30 · Nice › Monaco › Eze',
    'frt.desc1': 'Notre tour signature longe la Méditerranée depuis Nice jusqu\'à Monaco, traversant les plus beaux panoramas de la Côte d\'Azur. Une immersion totale dans la Riviera la plus glamour du monde.',
    'frt.desc2': 'Via la Corniche et les villages perchés, vous découvrirez des endroits que seul un side-car peut atteindre : ruelles médiévales d\'Èze, vue imprenable depuis La Turbie, et l\'effervescence de Monaco.',
    'frt.stop1': 'Nice — Point de départ',
    'frt.stop2': 'Beaulieu-sur-Mer',
    'frt.stop3': 'Cap d\'Ail',
    'frt.stop4': 'Monaco — Casino & Circuit F1',
    'frt.stop5': 'Grande Corniche',
    'frt.stop6': 'La Turbie — Trophée d\'Auguste',
    'frt.stop7': 'Èze — Village médiéval perché',
    'frt.book.h2': 'La Riviera vous appelle',
    'frt.book.script': 'Monaco et au-delà',
    'frt.book.lead': 'Réservez votre French Riviera City Tour pour une escapade inoubliable.',
    'nbn.eyebrow': 'Balade nocturne · La magie du soir',
    'nbn.script': 'Nice sous les étoiles',
    'nbn.badge': '🌙 Soirée · Nice illuminée',
    'nbn.desc1': 'La nuit transforme Nice en un tableau de lumières. À bord de votre side-car vintage, glissez le long de la Promenade des Anglais illuminée et ressentez l\'âme de la ville sous les étoiles.',
    'nbn.desc2': 'Une expérience sensorielle unique : le ronronnement du moteur, la brise marine du soir, et la Côte d\'Azur qui scintille autour de vous. Une parenthèse magique à vivre absolument.',
    'nbn.stop1': 'Promenade des Anglais illuminée',
    'nbn.stop2': 'Cœur de Vieux-Nice by night',
    'nbn.stop3': 'Port de Nice & ses reflets',
    'nbn.stop4': 'Points de vue nocturnes secrets',
    'nbn.stop5': 'Panoramas & lumières de la Côte',
    'nbn.book.h2': 'La nuit vous appartient',
    'nbn.book.script': 'Nice sous les étoiles',
    'nbn.book.lead': 'Réservez votre balade nocturne pour une expérience hors du commun.',
    'nbn.avail': 'Soirées sur réservation',
    'float.book': 'Réserver',
  },

  en: {
    'nav.home': 'Home',
    'nav.tours': 'City Tours ▾',
    'nav.tour.nice': 'Nice: City Tour',
    'nav.tour.riviera': 'French Riviera City Tour',
    'nav.tour.night': 'Nice by Night',
    'nav.events': 'Events',
    'nav.reviews': 'Reviews',
    'nav.contact': 'Contact',
    'nav.book': 'Book Now',
    'hero.eyebrow': 'Nice · Monaco · Côte d\'Azur',
    'hero.script': 'the great escape',
    'hero.sub': 'An authentic and unforgettable experience aboard vintage sidecars, between turquoise sea, hilltop villages and southern light.',
    'hero.book': 'Book my tour',
    'hero.discover': 'Discover our tours',
    'hero.scroll': 'Scroll',
    'intro.eyebrow': 'The great escape',
    'intro.title': 'Dive into the soul of the <em>Côte d\'Azur</em>',
    'intro.p1': 'Come and explore Nice and the French Riviera aboard our sidecars! Let yourself be driven by an experienced driver and enjoy the beauty of the landscapes.',
    'intro.p2': 'Our sidecar rides are far more than a simple tourist visit: it\'s a dive into the soul of the Côte d\'Azur, a journey through time and space that awakens all the senses. Between sea and mountains, medieval villages and chic seaside resorts, each stop is a new discovery.',
    'intro.p3': 'Hop on board, let yourself be lulled by the purr of the engine, the sea breeze in your hair, and admire the charm of the Riviera for unforgettable memories.',
    'intro.stamp.since': 'Since',
    'tours.eyebrow': 'Our signature itineraries',
    'tours.title': 'Three <em>rides</em> to experience the Riviera',
    'tours.lead': 'From Nice to Monaco, from the Promenade des Anglais to hilltop villages, each tour is designed to reveal the magic of the Côte d\'Azur.',
    'tours.more': 'More info',
    'tours.night': 'Night',
    'tour1.title': 'Nice City Tour',
    'tour1.desc': 'Visit the must-see sights of Nissa la Bella: Place Masséna, Nice Harbour, Mont-Boron, Villefranche-sur-Mer and the famous La Réserve diving board.',
    'tour2.title': 'French Riviera',
    'tour2.desc': 'The complete Côte d\'Azur itinerary: Beaulieu-sur-Mer, Cap d\'Ail, Monaco, the F1 circuit, the Grande Corniche, La Turbie and Èze, a perched medieval village.',
    'tour3.title': 'Nice by Night',
    'tour3.desc': 'Nice transforms at nightfall. Stroll along the illuminated Promenade des Anglais, with the gentle sea breeze and the lights reflected on the sea. Magic guaranteed.',
    'exp.eyebrow': 'The Riviera experience',
    'exp.title': 'Five promises, <em>one unique journey</em>',
    'feat1.title': 'Comfort & Safety',
    'feat1.desc': 'A modern vehicle with a vintage style, equipped with the latest safety technologies.',
    'feat2.title': 'Panoramic View',
    'feat2.desc': 'Seated in the sidecar, you have an unobstructed view of the landscapes — perfect for memorable photos.',
    'feat3.title': 'Exclusive Access',
    'feat3.desc': 'The sidecar slips through narrow streets and picturesque paths inaccessible to cars.',
    'feat4.title': 'Local Guide',
    'feat4.desc': 'Your driver is passionate about the region, ready to share anecdotes and secrets of the Riviera.',
    'feat5.title': 'Authenticity',
    'feat5.desc': 'Relive the golden age of sidecar travel — nostalgic, elegant, timeless.',
    'events.eyebrow': 'Tailor-made',
    'events.title': 'For your most <em>beautiful days</em>',
    'events.lead': 'We adapt to all your special requests. Listening to your wishes, we will do our best to satisfy you.',
    'events.item1': 'Weddings & bridal processions',
    'events.item2': 'Bachelor & bachelorette parties',
    'events.item3': 'Corporate events & seminars',
    'events.item4': 'Tasting of local products with <a href="https://www.restaurant-lou-bantry.fr/" style="color:var(--gold-2); text-decoration:underline;">Lou Bantry</a>',
    'events.item5': 'Pick-up at the location of your choice (no surcharge in Nice)',
    'events.cta': 'Contact us',
    'press.head': 'They talk about us',
    'press.quote': 'A retro "French-style" visit that reveals the Riviera from an unexpected and terribly charming angle.',
    'press.article': '« Sidecar rides to discover the Côte d\'Azur differently »',
    'test.eyebrow': 'Our clients speak for us',
    'test.title': 'Memories that <em>last</em>',
    'test1': '« Superb vintage sidecar ride! A memorable experience! »',
    'test2': '« A magical visit aboard the sidecar! Franck is passionate and it shows! »',
    'test3': '« An unforgettable experience through Nice with a super friendly guide. »',
    'test1.author': 'GetYourGuide Traveller',
    'test1.country': 'United States',
    'test2.country': 'Canada',
    'test3.country': 'Italy',
    'contact.title': 'Ready to embark?',
    'contact.script': 'your adventure starts here',
    'contact.lead': 'Book your ride or contact us for a tailor-made request. We will be delighted to share the Riviera with you.',
    'contact.book': 'Book online',
    'contact.instagram': 'Follow on Instagram',
    'footer.brand': 'The great escape on the Côte d\'Azur. Authentic vintage sidecar rides between Nice, Monaco and the French Riviera.',
    'footer.nav': 'Navigation',
    'footer.nav.tours': 'Our City Tours',
    'footer.reviews': 'Guest reviews',
    'footer.tours.title': 'Our tours',
    'footer.book': 'Booking',
    'footer.contact.title': 'Contact',
    'footer.copyright': '© {year} Riviera Sidecar — All rights reserved',
    'footer.deco': 'the great escape',
    'tour.practical': 'Practical info',
    'tour.included': 'What\'s included',
    'tour.itinerary': 'The itinerary',
    'tour.book.now': 'Book now',
    'tour.back': '← Back to tours',
    'tour.other.tours': 'Our other tours',
    'tour.label.duration': 'Duration',
    'tour.label.depart': 'Departure',
    'tour.label.lang': 'Languages',
    'tour.label.group': 'Group size',
    'tour.label.avail': 'Availability',
    'tour.avail.year': 'Year-round, on booking',
    'tour.avail.night': 'Evenings, on booking',
    'tour.group.value': 'Up to 2 passengers',
    'tour.lang.value': 'FR · EN · IT',
    'tour.depart.value': 'Nice Centre (flexible address)',
    'tour.inc.helmet': 'Helmet & protective goggles',
    'tour.inc.guide': 'Passionate guide-driver',
    'tour.inc.photos': 'Complimentary souvenir photos',
    'tour.inc.pickup': 'Flexible pick-up location',
    'tour.inc.insurance': 'Passenger insurance included',
    'tour.inc.equip': 'Full equipment provided',
    'nct.eyebrow': 'Vintage ride · 1h15',
    'nct.script': 'Nissa la Bella',
    'nct.badge': '⏱ 1h15 · Nice & surroundings',
    'nct.desc1': 'Explore the treasures of Nice at the rhythm of a purring vintage sidecar. Your passionate guide-driver takes you to discover Nissa la Bella, from the Promenade des Anglais to the bay of Villefranche-sur-Mer.',
    'nct.desc2': 'One hour and fifteen minutes of wonder between sea and hills, from the medieval Old Town to the breathtaking panoramas of Mont-Boron, all the way to the famous La Réserve diving board.',
    'nct.stop1': 'Promenade des Anglais',
    'nct.stop2': 'Place Masséna & Old Nice',
    'nct.stop3': 'Port of Nice',
    'nct.stop4': 'Mont-Boron — Panorama over the Bay',
    'nct.stop5': 'Villefranche-sur-Mer',
    'nct.stop6': 'La Réserve diving board',
    'nct.book.h2': 'Ready for adventure?',
    'nct.book.script': 'Nice awaits you',
    'nct.book.lead': 'Book your Nice City Tour and experience the Riviera differently.',
    'frt.eyebrow': 'Signature ride · 2h30',
    'frt.script': 'From Nice to Monaco',
    'frt.badge': '⏱ 2h30 · Nice › Monaco › Eze',
    'frt.desc1': 'Our signature tour hugs the Mediterranean from Nice to Monaco, crossing the most beautiful panoramas of the Côte d\'Azur. A total immersion in the world\'s most glamorous Riviera.',
    'frt.desc2': 'Via the Corniche and perched villages, you\'ll discover places only a sidecar can reach: medieval alleyways of Èze, breathtaking views from La Turbie, and the unique buzz of Monaco.',
    'frt.stop1': 'Nice — Starting point',
    'frt.stop2': 'Beaulieu-sur-Mer',
    'frt.stop3': 'Cap d\'Ail',
    'frt.stop4': 'Monaco — Casino & F1 Circuit',
    'frt.stop5': 'Grande Corniche',
    'frt.stop6': 'La Turbie — Augustus\' Trophy',
    'frt.stop7': 'Èze — Perched medieval village',
    'frt.book.h2': 'The Riviera is calling',
    'frt.book.script': 'Monaco and beyond',
    'frt.book.lead': 'Book your French Riviera City Tour for an unforgettable escape.',
    'nbn.eyebrow': 'Night ride · The magic of evening',
    'nbn.script': 'Nice under the stars',
    'nbn.badge': '🌙 Evening · Illuminated Nice',
    'nbn.desc1': 'Night transforms Nice into a painting of lights. Aboard your vintage sidecar, glide along the illuminated Promenade des Anglais and feel the soul of the city under the stars.',
    'nbn.desc2': 'A unique sensory experience: the purr of the engine, the evening sea breeze, and the Côte d\'Azur sparkling all around you. A magical interlude you absolutely must experience.',
    'nbn.stop1': 'Illuminated Promenade des Anglais',
    'nbn.stop2': 'Old Nice by night',
    'nbn.stop3': 'Port of Nice & its reflections',
    'nbn.stop4': 'Secret nocturnal viewpoints',
    'nbn.stop5': 'Riviera panoramas & lights',
    'nbn.book.h2': 'The night is yours',
    'nbn.book.script': 'Nice under the stars',
    'nbn.book.lead': 'Book your night ride for an extraordinary experience.',
    'nbn.avail': 'Evenings, on booking',
    'float.book': 'Book',
  },

  de: {
    'nav.home': 'Startseite',
    'nav.tours': 'City Tours ▾',
    'nav.tour.nice': 'Nizza: City Tour',
    'nav.tour.riviera': 'French Riviera City Tour',
    'nav.tour.night': 'Nizza bei Nacht',
    'nav.events': 'Veranstaltungen',
    'nav.reviews': 'Bewertungen',
    'nav.contact': 'Kontakt',
    'nav.book': 'Buchen',
    'hero.eyebrow': 'Nizza · Monaco · Côte d\'Azur',
    'hero.script': 'die große Flucht',
    'hero.sub': 'Ein authentisches und unvergessliches Erlebnis an Bord von Vintage-Beiwagen, zwischen türkisfarbenem Meer, Bergdörfern und südlichem Licht.',
    'hero.book': 'Meine Tour buchen',
    'hero.discover': 'Touren entdecken',
    'hero.scroll': 'Scrollen',
    'intro.eyebrow': 'Die große Flucht',
    'intro.title': 'Tauchen Sie ein in die Seele der <em>Côte d\'Azur</em>',
    'intro.p1': 'Besuchen Sie Nizza und die Französische Riviera an Bord unserer Beiwagen! Lassen Sie sich von einem erfahrenen Fahrer führen und genießen Sie die Schönheit der Landschaften.',
    'intro.p2': 'Unsere Beiwagen-Ausflüge sind weit mehr als ein einfacher Touristenbesuch: Es ist ein Eintauchen in die Seele der Côte d\'Azur, eine Reise durch Zeit und Raum, die alle Sinne weckt. Zwischen Meer und Bergen, mittelalterlichen Dörfern und schicken Badeorten ist jeder Halt eine neue Entdeckung.',
    'intro.p3': 'Steigen Sie ein, lassen Sie sich vom Schnurren des Motors und der Meeresbrise in den Haaren wiegen und bewundern Sie den Charme der Riviera für unvergessliche Erinnerungen.',
    'intro.stamp.since': 'Seit',
    'tours.eyebrow': 'Unsere Signature-Routen',
    'tours.title': 'Drei <em>Ausfahrten</em> um die Riviera zu erleben',
    'tours.lead': 'Von Nizza bis Monaco, von der Promenade des Anglais bis zu den Bergdörfern — jede Tour enthüllt die Magie der Côte d\'Azur.',
    'tours.more': 'Mehr erfahren',
    'tours.night': 'Nacht',
    'tour1.title': 'Nizza City Tour',
    'tour1.desc': 'Besuchen Sie die Sehenswürdigkeiten von Nissa la Bella: Place Masséna, Hafen von Nizza, Mont-Boron, Villefranche-sur-Mer und das berühmte Sprungbrett von La Réserve.',
    'tour2.title': 'Französische Riviera',
    'tour2.desc': 'Die komplette Côte d\'Azur Route: Beaulieu-sur-Mer, Cap d\'Ail, Monaco, die F1-Strecke, die Grande Corniche, La Turbie und Èze, ein mittelalterliches Bergdorf.',
    'tour3.title': 'Nizza bei Nacht',
    'tour3.desc': 'Nizza verwandelt sich bei Einbruch der Nacht. Schlendern Sie entlang der beleuchteten Promenade des Anglais mit der sanften Meeresbrise und den Lichtern, die sich im Meer spiegeln. Magie garantiert.',
    'exp.eyebrow': 'Das Riviera-Erlebnis',
    'exp.title': 'Fünf Versprechen, <em>eine einzigartige Reise</em>',
    'feat1.title': 'Komfort & Sicherheit',
    'feat1.desc': 'Ein modernes Fahrzeug im Vintage-Stil, ausgestattet mit den neuesten Sicherheitstechnologien.',
    'feat2.title': 'Panoramablick',
    'feat2.desc': 'Im Beiwagen sitzend haben Sie einen ungehinderten Blick auf die Landschaften — ideal für unvergessliche Fotos.',
    'feat3.title': 'Exklusiver Zugang',
    'feat3.desc': 'Der Beiwagen schlängelt sich durch enge Gassen und malerische Wege, die für Autos unzugänglich sind.',
    'feat4.title': 'Ortskundiger Führer',
    'feat4.desc': 'Ihr Fahrer ist ein Kenner der Region und bereit, Anekdoten und Geheimnisse der Riviera zu teilen.',
    'feat5.title': 'Authentizität',
    'feat5.desc': 'Erleben Sie das goldene Zeitalter des Beiwagen-Reisens — nostalgisch, elegant, zeitlos.',
    'events.eyebrow': 'Maßgeschneidert',
    'events.title': 'Für Ihre schönsten <em>Momente</em>',
    'events.lead': 'Wir passen uns allen Ihren besonderen Wünschen an und tun unser Bestes, um Sie zufriedenzustellen.',
    'events.item1': 'Hochzeiten & Hochzeitskorso',
    'events.item2': 'Junggesellenabschiede',
    'events.item3': 'Firmenveranstaltungen & Seminare',
    'events.item4': 'Verkostung lokaler Produkte mit <a href="https://www.restaurant-lou-bantry.fr/" style="color:var(--gold-2); text-decoration:underline;">Lou Bantry</a>',
    'events.item5': 'Abholung am Ort Ihrer Wahl (kein Aufpreis in Nizza)',
    'events.cta': 'Kontakt aufnehmen',
    'press.head': 'Sie berichten über uns',
    'press.quote': 'Ein retro-französischer Besuch, der die Riviera aus einem unerwarteten und unglaublich charmanten Blickwinkel enthüllt.',
    'press.article': '« Beiwagentouren, um die Côte d\'Azur anders zu entdecken »',
    'test.eyebrow': 'Unsere Kunden sprechen für uns',
    'test.title': 'Erinnerungen, die <em>bleiben</em>',
    'test1': '« Herrliche Fahrt im Vintage-Beiwagen! Ein unvergessliches Erlebnis! »',
    'test2': '« Ein magischer Besuch im Beiwagen! Franck ist leidenschaftlich und das merkt man! »',
    'test3': '« Ein unvergessliches Erlebnis durch Nizza mit einem super freundlichen Guide. »',
    'test1.author': 'GetYourGuide-Reisender',
    'test1.country': 'Vereinigte Staaten',
    'test2.country': 'Kanada',
    'test3.country': 'Italien',
    'contact.title': 'Bereit zum Einsteigen?',
    'contact.script': 'Ihr Abenteuer beginnt hier',
    'contact.lead': 'Buchen Sie Ihre Tour oder kontaktieren Sie uns für eine individuelle Anfrage. Wir freuen uns, die Riviera mit Ihnen zu teilen.',
    'contact.book': 'Online buchen',
    'contact.instagram': 'Auf Instagram folgen',
    'footer.brand': 'Die große Flucht an der Côte d\'Azur. Authentische Vintage-Beiwagen-Fahrten zwischen Nizza, Monaco und der Französischen Riviera.',
    'footer.nav': 'Navigation',
    'footer.nav.tours': 'Unsere City Tours',
    'footer.reviews': 'Gästebewertungen',
    'footer.tours.title': 'Unsere Touren',
    'footer.book': 'Buchung',
    'footer.contact.title': 'Kontakt',
    'footer.copyright': '© {year} Riviera Sidecar — Alle Rechte vorbehalten',
    'footer.deco': 'die große Flucht',
    'tour.practical': 'Praktische Infos',
    'tour.included': 'Im Preis enthalten',
    'tour.itinerary': 'Die Route',
    'tour.book.now': 'Jetzt buchen',
    'tour.back': '← Zurück zu Touren',
    'tour.other.tours': 'Unsere anderen Touren',
    'tour.label.duration': 'Dauer',
    'tour.label.depart': 'Abfahrt',
    'tour.label.lang': 'Sprachen',
    'tour.label.group': 'Gruppe',
    'tour.label.avail': 'Verfügbarkeit',
    'tour.avail.year': 'Ganzjährig auf Anfrage',
    'tour.avail.night': 'Abends auf Anfrage',
    'tour.group.value': 'Bis zu 2 Passagiere',
    'tour.lang.value': 'FR · EN · IT',
    'tour.depart.value': 'Nizza Zentrum (flexibler Abholort)',
    'tour.inc.helmet': 'Helm & Schutzbrille',
    'tour.inc.guide': 'Leidenschaftlicher Guide',
    'tour.inc.photos': 'Erinnerungsfotos inklusive',
    'tour.inc.pickup': 'Flexible Abholadresse',
    'tour.inc.insurance': 'Passagierversicherung inklusive',
    'tour.inc.equip': 'Vollständige Ausrüstung',
    'nct.eyebrow': 'Vintage-Tour · 1h15',
    'nct.script': 'Nissa la Bella',
    'nct.badge': '⏱ 1h15 · Nizza & Umgebung',
    'nct.desc1': 'Erkunden Sie die Schätze von Nizza im Rhythmus des Schnurrens eines Vintage-Beiwagens. Ihr begeisterter Fahrer-Guide nimmt Sie mit auf eine Entdeckungstour durch Nissa la Bella.',
    'nct.desc2': 'Eineinviertel Stunden Staunen zwischen Meer und Hügeln, von der mittelalterlichen Altstadt über die atemberaubenden Panoramen des Mont-Boron bis zum berühmten Sprungbrett von La Réserve.',
    'nct.stop1': 'Promenade des Anglais',
    'nct.stop2': 'Place Masséna & Altstadt',
    'nct.stop3': 'Hafen von Nizza',
    'nct.stop4': 'Mont-Boron — Panorama über die Bucht',
    'nct.stop5': 'Villefranche-sur-Mer',
    'nct.stop6': 'Sprungbrett von La Réserve',
    'nct.book.h2': 'Bereit für das Abenteuer?',
    'nct.book.script': 'Nizza wartet auf Sie',
    'nct.book.lead': 'Buchen Sie Ihre Nizza City Tour und erleben Sie die Riviera anders.',
    'frt.eyebrow': 'Signature-Tour · 2h30',
    'frt.script': 'Von Nizza nach Monaco',
    'frt.badge': '⏱ 2h30 · Nizza › Monaco › Eze',
    'frt.desc1': 'Unsere Signature-Tour folgt dem Mittelmeer von Nizza bis Monaco und durchquert die schönsten Panoramen der Côte d\'Azur. Eine totale Immersion in die glamouröseste Riviera der Welt.',
    'frt.desc2': 'Über die Corniche und Bergdörfer entdecken Sie Orte, die nur ein Beiwagen erreichen kann: mittelalterliche Gassen von Èze, atemberaubende Ausblicke von La Turbie, und das einzigartige Monaco.',
    'frt.stop1': 'Nizza — Startpunkt',
    'frt.stop2': 'Beaulieu-sur-Mer',
    'frt.stop3': 'Cap d\'Ail',
    'frt.stop4': 'Monaco — Casino & F1-Strecke',
    'frt.stop5': 'Grande Corniche',
    'frt.stop6': 'La Turbie — Augustustrophäe',
    'frt.stop7': 'Èze — Mittelalterliches Bergdorf',
    'frt.book.h2': 'Die Riviera ruft',
    'frt.book.script': 'Monaco und darüber hinaus',
    'frt.book.lead': 'Buchen Sie Ihre French Riviera City Tour für ein unvergessliches Erlebnis.',
    'nbn.eyebrow': 'Nacht-Tour · Die Magie des Abends',
    'nbn.script': 'Nizza unter den Sternen',
    'nbn.badge': '🌙 Abend · Beleuchtetes Nizza',
    'nbn.desc1': 'Die Nacht verwandelt Nizza in ein Gemälde aus Lichtern. Gleiten Sie in Ihrem Vintage-Beiwagen entlang der beleuchteten Promenade des Anglais und spüren Sie die Seele der Stadt unter den Sternen.',
    'nbn.desc2': 'Ein einzigartiges Sinneserlebnis: das Schnurren des Motors, die Abendbrise vom Meer, und die Côte d\'Azur, die um Sie herum funkelt. Ein magischer Moment, den Sie unbedingt erleben müssen.',
    'nbn.stop1': 'Beleuchtete Promenade des Anglais',
    'nbn.stop2': 'Altstadt bei Nacht',
    'nbn.stop3': 'Hafen von Nizza & seine Spiegelungen',
    'nbn.stop4': 'Geheime Nachtausblicke',
    'nbn.stop5': 'Riviera-Panoramen & Lichter',
    'nbn.book.h2': 'Die Nacht gehört Ihnen',
    'nbn.book.script': 'Nizza unter den Sternen',
    'nbn.book.lead': 'Buchen Sie Ihre Nachttour für ein außergewöhnliches Erlebnis.',
    'nbn.avail': 'Abends auf Anfrage',
    'float.book': 'Buchen',
  },

  it: {
    'nav.home': 'Home',
    'nav.tours': 'City Tours ▾',
    'nav.tour.nice': 'Nizza: City Tour',
    'nav.tour.riviera': 'French Riviera City Tour',
    'nav.tour.night': 'Nizza di Notte',
    'nav.events': 'Eventi',
    'nav.reviews': 'Recensioni',
    'nav.contact': 'Contatto',
    'nav.book': 'Prenota',
    'hero.eyebrow': 'Nizza · Monaco · Côte d\'Azur',
    'hero.script': 'la grande fuga',
    'hero.sub': 'Un\'esperienza autentica e indimenticabile a bordo di sidecar vintage, tra mare turchese, borghi arroccati e luce del Sud.',
    'hero.book': 'Prenota il mio tour',
    'hero.discover': 'Scopri i tour',
    'hero.scroll': 'Scorri',
    'intro.eyebrow': 'La grande fuga',
    'intro.title': 'Immergiti nell\'anima della <em>Côte d\'Azur</em>',
    'intro.p1': 'Venite a visitare Nizza e la French Riviera a bordo dei nostri sidecar! Lasciatevi condurre da un autista esperto e godetevi la bellezza dei paesaggi.',
    'intro.p2': 'I nostri giri in sidecar sono molto più di una semplice visita turistica: è un\'immersione nell\'anima della Côte d\'Azur, un viaggio nel tempo e nello spazio che risveglia tutti i sensi. Tra mare e montagna, borghi medievali e chic stazioni balneari, ogni tappa è una nuova scoperta.',
    'intro.p3': 'Salite a bordo, lasciatevi cullare dal ronzio del motore, dalla brezza marina tra i capelli, e ammirate il fascino della Riviera per ricordi indelebili.',
    'intro.stamp.since': 'Dal',
    'tours.eyebrow': 'I nostri itinerari signature',
    'tours.title': 'Tre <em>gite</em> per vivere la Riviera',
    'tours.lead': 'Da Nizza a Monaco, dalla Promenade des Anglais ai borghi arroccati, ogni tour svela la magia della Côte d\'Azur.',
    'tours.more': 'Più informazioni',
    'tours.night': 'Notte',
    'tour1.title': 'Nizza City Tour',
    'tour1.desc': 'Visitate i luoghi imperdibili di Nissa la Bella: Piazza Masséna, Porto di Nizza, Mont-Boron, Villefranche-sur-Mer e il famoso trampolino di La Réserve.',
    'tour2.title': 'Costa Azzurra',
    'tour2.desc': 'L\'itinerario completo della Côte d\'Azur: Beaulieu-sur-Mer, Cap d\'Ail, Monaco, il circuito di F1, la Grande Corniche, La Turbie ed Èze, borgo medievale arroccato.',
    'tour3.title': 'Nizza di Notte',
    'tour3.desc': 'Nizza si trasforma al calar della notte. Passeggiate lungo la Promenade des Anglais illuminata, con la dolce brezza marina e le luci che si riflettono sul mare. Magia assicurata.',
    'exp.eyebrow': 'L\'esperienza Riviera',
    'exp.title': 'Cinque promesse, <em>un viaggio unico</em>',
    'feat1.title': 'Comfort & Sicurezza',
    'feat1.desc': 'Un veicolo moderno in stile vintage, dotato delle ultime tecnologie in materia di sicurezza.',
    'feat2.title': 'Vista Panoramica',
    'feat2.desc': 'Seduti nel sidecar, avete una vista libera sui paesaggi — ideale per foto memorabili.',
    'feat3.title': 'Accesso Esclusivo',
    'feat3.desc': 'Il sidecar si insinua nei vicoli e nei sentieri pittoreschi inaccessibili alle auto.',
    'feat4.title': 'Guida Locale',
    'feat4.desc': 'Il vostro autista è un appassionato della regione, pronto a condividere aneddoti e segreti della Riviera.',
    'feat5.title': 'Autenticità',
    'feat5.desc': 'Rivivete l\'età dell\'oro dei viaggi in sidecar — nostalgico, elegante, senza tempo.',
    'events.eyebrow': 'Su misura',
    'events.title': 'Per i vostri giorni più <em>belli</em>',
    'events.lead': 'Ci adattiamo a tutte le vostre richieste particolari. In ascolto dei vostri desideri, faremo del nostro meglio per soddisfarvi.',
    'events.item1': 'Matrimoni & cortei nuziali',
    'events.item2': 'Addio al celibato / nubilato',
    'events.item3': 'Eventi aziendali & seminari',
    'events.item4': 'Degustazione di prodotti locali con <a href="https://www.restaurant-lou-bantry.fr/" style="color:var(--gold-2); text-decoration:underline;">Lou Bantry</a>',
    'events.item5': 'Presa in carico nel luogo di vostra scelta (senza supplemento su Nizza)',
    'events.cta': 'Contattaci',
    'press.head': 'Parlano di noi',
    'press.quote': 'Una visita retrò "alla francese" che rivela la Riviera da un\'angolazione inaspettata e incredibilmente affascinante.',
    'press.article': '« Gite in sidecar per scoprire la Côte d\'Azur in modo diverso »',
    'test.eyebrow': 'I nostri clienti parlano di noi',
    'test.title': 'Ricordi che <em>durano</em>',
    'test1': '« Superba gita in sidecar vintage! Un\'esperienza memorabile! »',
    'test2': '« Una visita magica a bordo del sidecar! Franck è appassionato e si vede! »',
    'test3': '« Un\'esperienza indimenticabile attraverso Nizza con una guida super simpatica. »',
    'test1.author': 'Viaggiatore GetYourGuide',
    'test1.country': 'Stati Uniti',
    'test2.country': 'Canada',
    'test3.country': 'Italia',
    'contact.title': 'Pronti a imbarcarvi?',
    'contact.script': 'la vostra avventura inizia qui',
    'contact.lead': 'Prenotate il vostro giro o contattateci per una richiesta su misura. Saremo lieti di condividere la Riviera con voi.',
    'contact.book': 'Prenota online',
    'contact.instagram': 'Segui su Instagram',
    'footer.brand': 'La grande fuga sulla Côte d\'Azur. Autentici giri in sidecar vintage tra Nizza, Monaco e la Riviera Francese.',
    'footer.nav': 'Navigazione',
    'footer.nav.tours': 'I nostri City Tours',
    'footer.reviews': 'Recensioni clienti',
    'footer.tours.title': 'I nostri tour',
    'footer.book': 'Prenotazione',
    'footer.contact.title': 'Contatto',
    'footer.copyright': '© {year} Riviera Sidecar — Tutti i diritti riservati',
    'footer.deco': 'la grande fuga',
    'tour.practical': 'Informazioni pratiche',
    'tour.included': 'Incluso nella gita',
    'tour.itinerary': 'L\'itinerario',
    'tour.book.now': 'Prenota ora',
    'tour.back': '← Torna ai tour',
    'tour.other.tours': 'I nostri altri tour',
    'tour.label.duration': 'Durata',
    'tour.label.depart': 'Partenza',
    'tour.label.lang': 'Lingue',
    'tour.label.group': 'Gruppo',
    'tour.label.avail': 'Disponibilità',
    'tour.avail.year': 'Tutto l\'anno su prenotazione',
    'tour.avail.night': 'Serate su prenotazione',
    'tour.group.value': 'Fino a 2 passeggeri',
    'tour.lang.value': 'FR · EN · IT',
    'tour.depart.value': 'Centro Nizza (indirizzo flessibile)',
    'tour.inc.helmet': 'Casco & occhiali protettivi',
    'tour.inc.guide': 'Guida-autista appassionata',
    'tour.inc.photos': 'Foto ricordo in omaggio',
    'tour.inc.pickup': 'Presa in carico flessibile',
    'tour.inc.insurance': 'Assicurazione passeggero inclusa',
    'tour.inc.equip': 'Attrezzatura completa fornita',
    'nct.eyebrow': 'Gita vintage · 1h15',
    'nct.script': 'Nissa la Bella',
    'nct.badge': '⏱ 1h15 · Nizza e dintorni',
    'nct.desc1': 'Esplorate i tesori di Nizza al ritmo del ronzio di un sidecar vintage. Il vostro autista-guida appassionato vi porta alla scoperta di Nissa la Bella, dalla Promenade des Anglais alla baia di Villefranche-sur-Mer.',
    'nct.desc2': 'Un\'ora e un quarto di meraviglia tra mare e colline, dal centro medievale ai panorami mozzafiato del Mont-Boron, fino al famoso trampolino di La Réserve.',
    'nct.stop1': 'Promenade des Anglais',
    'nct.stop2': 'Place Masséna & Città Vecchia',
    'nct.stop3': 'Porto di Nizza',
    'nct.stop4': 'Mont-Boron — Panorama sulla Rada',
    'nct.stop5': 'Villefranche-sur-Mer',
    'nct.stop6': 'Trampolino di La Réserve',
    'nct.book.h2': 'Pronti all\'avventura?',
    'nct.book.script': 'Nizza vi aspetta',
    'nct.book.lead': 'Prenotate il vostro Nizza City Tour e vivete la Riviera in modo diverso.',
    'frt.eyebrow': 'Gita signature · 2h30',
    'frt.script': 'Da Nizza a Monaco',
    'frt.badge': '⏱ 2h30 · Nizza › Monaco › Eze',
    'frt.desc1': 'Il nostro tour signature segue il Mediterraneo da Nizza a Monaco, attraversando i più bei panorami della Costa Azzurra. Un\'immersione totale nella Riviera più glamour del mondo.',
    'frt.desc2': 'Attraverso la Corniche e i borghi arroccati, scoprirete luoghi raggiungibili solo in sidecar: vicoli medievali di Èze, vista mozzafiato da La Turbie, e l\'effervescenza unica di Monaco.',
    'frt.stop1': 'Nizza — Punto di partenza',
    'frt.stop2': 'Beaulieu-sur-Mer',
    'frt.stop3': 'Cap d\'Ail',
    'frt.stop4': 'Monaco — Casinò & Circuito F1',
    'frt.stop5': 'Grande Corniche',
    'frt.stop6': 'La Turbie — Trofeo di Augusto',
    'frt.stop7': 'Èze — Borgo medievale arroccato',
    'frt.book.h2': 'La Riviera vi chiama',
    'frt.book.script': 'Monaco e oltre',
    'frt.book.lead': 'Prenotate il vostro French Riviera City Tour per una fuga indimenticabile.',
    'nbn.eyebrow': 'Gita notturna · La magia della sera',
    'nbn.script': 'Nizza sotto le stelle',
    'nbn.badge': '🌙 Sera · Nizza illuminata',
    'nbn.desc1': 'La notte trasforma Nizza in un quadro di luci. A bordo del vostro sidecar vintage, scivolate lungo la Promenade des Anglais illuminata e sentite l\'anima della città sotto le stelle.',
    'nbn.desc2': 'Un\'esperienza sensoriale unica: il ronzio del motore, la brezza marina serale, e la Costa Azzurra che scintilla intorno a voi. Un momento magico da vivere assolutamente.',
    'nbn.stop1': 'Promenade des Anglais illuminata',
    'nbn.stop2': 'Città Vecchia di notte',
    'nbn.stop3': 'Porto di Nizza e i suoi riflessi',
    'nbn.stop4': 'Punti panoramici notturni segreti',
    'nbn.stop5': 'Panorami e luci della Riviera',
    'nbn.book.h2': 'La notte è vostra',
    'nbn.book.script': 'Nizza sotto le stelle',
    'nbn.book.lead': 'Prenotate la vostra gita notturna per un\'esperienza straordinaria.',
    'nbn.avail': 'Serate su prenotazione',
    'float.book': 'Prenota',
  },

  es: {
    'nav.home': 'Inicio',
    'nav.tours': 'City Tours ▾',
    'nav.tour.nice': 'Niza: City Tour',
    'nav.tour.riviera': 'French Riviera City Tour',
    'nav.tour.night': 'Niza de Noche',
    'nav.events': 'Eventos',
    'nav.reviews': 'Opiniones',
    'nav.contact': 'Contacto',
    'nav.book': 'Reservar',
    'hero.eyebrow': 'Niza · Mónaco · Côte d\'Azur',
    'hero.script': 'la gran escapada',
    'hero.sub': 'Una experiencia auténtica e inolvidable a bordo de sidecars vintage, entre el mar turquesa, pueblos encaramados y la luz del Sur.',
    'hero.book': 'Reservar mi tour',
    'hero.discover': 'Descubrir los tours',
    'hero.scroll': 'Desplazar',
    'intro.eyebrow': 'La gran escapada',
    'intro.title': 'Sumérjase en el alma de la <em>Côte d\'Azur</em>',
    'intro.p1': '¡Venga a visitar Niza y la Riviera Francesa a bordo de nuestros sidecars! Déjese llevar por un conductor experimentado y disfrute de la belleza de los paisajes.',
    'intro.p2': 'Nuestros paseos en sidecar son mucho más que una simple visita turística: es una inmersión en el alma de la Côte d\'Azur, un viaje en el tiempo y el espacio que despierta todos los sentidos. Entre el mar y la montaña, pueblos medievales y elegantes estaciones balnearias, cada etapa es un nuevo descubrimiento.',
    'intro.p3': 'Súbase a bordo, déjese mecer por el ronroneo del motor, la brisa marina en su cabello, y admire el encanto de la Riviera para recuerdos imperecederos.',
    'intro.stamp.since': 'Desde',
    'tours.eyebrow': 'Nuestros itinerarios estrella',
    'tours.title': 'Tres <em>paseos</em> para vivir la Riviera',
    'tours.lead': 'De Niza a Mónaco, de la Promenade des Anglais a los pueblos encaramados, cada tour revela la magia de la Côte d\'Azur.',
    'tours.more': 'Más información',
    'tours.night': 'Noche',
    'tour1.title': 'Niza City Tour',
    'tour1.desc': 'Visite los lugares imprescindibles de Nissa la Bella: Place Masséna, Puerto de Niza, Mont-Boron, Villefranche-sur-Mer y el famoso trampolín de La Réserve.',
    'tour2.title': 'Riviera Francesa',
    'tour2.desc': 'El itinerario completo de la Côte d\'Azur: Beaulieu-sur-Mer, Cap d\'Ail, Mónaco, el circuito de F1, la Grande Corniche, La Turbie y Èze, pueblo medieval encaramado.',
    'tour3.title': 'Niza de Noche',
    'tour3.desc': 'Niza se transforma al caer la noche. Pasee por la iluminada Promenade des Anglais, con la suave briza marina y las luces reflejadas en el mar. Magia garantizada.',
    'exp.eyebrow': 'La experiencia Riviera',
    'exp.title': 'Cinco promesas, <em>un viaje único</em>',
    'feat1.title': 'Comodidad & Seguridad',
    'feat1.desc': 'Un vehículo moderno de estilo vintage, equipado con las últimas tecnologías en materia de seguridad.',
    'feat2.title': 'Vista Panorámica',
    'feat2.desc': 'Sentado en el sidecar, tiene una vista despejada de los paisajes — ideal para fotos memorables.',
    'feat3.title': 'Acceso Exclusivo',
    'feat3.desc': 'El sidecar se cuela por callejuelas y caminos pintorescos inaccesibles para los coches.',
    'feat4.title': 'Guía Local',
    'feat4.desc': 'Su conductor es un apasionado de la región, listo para compartir anécdotas y secretos de la Riviera.',
    'feat5.title': 'Autenticidad',
    'feat5.desc': 'Reviva la edad de oro de los viajes en sidecar — nostálgico, elegante, atemporal.',
    'events.eyebrow': 'A medida',
    'events.title': 'Para sus días más <em>especiales</em>',
    'events.lead': 'Nos adaptamos a todas sus peticiones particulares. Escuchando sus deseos, haremos lo posible para satisfacerle.',
    'events.item1': 'Bodas & cortejo nupcial',
    'events.item2': 'Despedidas de soltero / de soltera',
    'events.item3': 'Eventos de empresa & seminarios',
    'events.item4': 'Degustación de productos locales con <a href="https://www.restaurant-lou-bantry.fr/" style="color:var(--gold-2); text-decoration:underline;">Lou Bantry</a>',
    'events.item5': 'Recogida en el lugar de su elección (sin suplemento en Niza)',
    'events.cta': 'Contáctenos',
    'press.head': 'Hablan de nosotros',
    'press.quote': 'Una visita retro «a la francesa» que revela la Riviera desde un ángulo inesperado y tremendamente encantador.',
    'press.article': '« Paseos en sidecar para descubrir la Côte d\'Azur de otra manera »',
    'test.eyebrow': 'Nuestros clientes hablan de nosotros',
    'test.title': 'Recuerdos que <em>perduran</em>',
    'test1': '« ¡Magnífico paseo en sidecar vintage! ¡Una experiencia memorable! »',
    'test2': '« ¡Una visita mágica a bordo del sidecar! ¡Franck es apasionado y se nota! »',
    'test3': '« Una experiencia inolvidable por Niza con un guía muy simpático. »',
    'test1.author': 'Viajero GetYourGuide',
    'test1.country': 'Estados Unidos',
    'test2.country': 'Canadá',
    'test3.country': 'Italia',
    'contact.title': '¿Listos para embarcar?',
    'contact.script': 'su aventura empieza aquí',
    'contact.lead': 'Reserve su paseo o contáctenos para una solicitud a medida. Estaremos encantados de compartir la Riviera con usted.',
    'contact.book': 'Reservar en línea',
    'contact.instagram': 'Seguir en Instagram',
    'footer.brand': 'La gran escapada en la Côte d\'Azur. Auténticos paseos en sidecar vintage entre Niza, Mónaco y la Riviera Francesa.',
    'footer.nav': 'Navegación',
    'footer.nav.tours': 'Nuestros City Tours',
    'footer.reviews': 'Opiniones de clientes',
    'footer.tours.title': 'Nuestros tours',
    'footer.book': 'Reserva',
    'footer.contact.title': 'Contacto',
    'footer.copyright': '© {year} Riviera Sidecar — Todos los derechos reservados',
    'footer.deco': 'la gran escapada',
    'tour.practical': 'Info práctica',
    'tour.included': 'Incluido en el paseo',
    'tour.itinerary': 'El itinerario',
    'tour.book.now': 'Reservar ahora',
    'tour.back': '← Volver a tours',
    'tour.other.tours': 'Nuestros otros tours',
    'tour.label.duration': 'Duración',
    'tour.label.depart': 'Salida',
    'tour.label.lang': 'Idiomas',
    'tour.label.group': 'Grupo',
    'tour.label.avail': 'Disponibilidad',
    'tour.avail.year': 'Todo el año bajo reserva',
    'tour.avail.night': 'Tardes bajo reserva',
    'tour.group.value': 'Hasta 2 pasajeros',
    'tour.lang.value': 'FR · EN · IT',
    'tour.depart.value': 'Centro Niza (dirección flexible)',
    'tour.inc.helmet': 'Casco & gafas protectoras',
    'tour.inc.guide': 'Guía-conductor apasionado',
    'tour.inc.photos': 'Fotos de recuerdo de regalo',
    'tour.inc.pickup': 'Recogida flexible',
    'tour.inc.insurance': 'Seguro de pasajero incluido',
    'tour.inc.equip': 'Equipamiento completo incluido',
    'nct.eyebrow': 'Paseo vintage · 1h15',
    'nct.script': 'Nissa la Bella',
    'nct.badge': '⏱ 1h15 · Niza y alrededores',
    'nct.desc1': 'Explore los tesoros de Niza al ritmo del ronroneo de un sidecar vintage. Su apasionado guía-conductor le lleva a descubrir Nissa la Bella, desde la Promenade des Anglais hasta la bahía de Villefranche-sur-Mer.',
    'nct.desc2': 'Una hora y cuarto de asombro entre el mar y las colinas, desde la ciudad medieval hasta los impresionantes panoramas del Mont-Boron, hasta el famoso trampolín de La Réserve.',
    'nct.stop1': 'Promenade des Anglais',
    'nct.stop2': 'Place Masséna & Casco Antiguo',
    'nct.stop3': 'Puerto de Niza',
    'nct.stop4': 'Mont-Boron — Panorama sobre la Rada',
    'nct.stop5': 'Villefranche-sur-Mer',
    'nct.stop6': 'Trampolín de La Réserve',
    'nct.book.h2': '¿Listos para la aventura?',
    'nct.book.script': 'Niza os espera',
    'nct.book.lead': 'Reserve su Niza City Tour y viva la Riviera de otra manera.',
    'frt.eyebrow': 'Paseo estrella · 2h30',
    'frt.script': 'De Niza a Mónaco',
    'frt.badge': '⏱ 2h30 · Niza › Mónaco › Eze',
    'frt.desc1': 'Nuestro tour estrella sigue el Mediterráneo de Niza a Mónaco, cruzando los más bellos panoramas de la Costa Azul. Una inmersión total en la Riviera más glamurosa del mundo.',
    'frt.desc2': 'A través de la Corniche y los pueblos encaramados, descubrirá lugares que solo un sidecar puede alcanzar: callejuelas medievales de Èze, vistas impresionantes desde La Turbie, y la efervescencia única de Mónaco.',
    'frt.stop1': 'Niza — Punto de salida',
    'frt.stop2': 'Beaulieu-sur-Mer',
    'frt.stop3': 'Cap d\'Ail',
    'frt.stop4': 'Mónaco — Casino & Circuito F1',
    'frt.stop5': 'Grande Corniche',
    'frt.stop6': 'La Turbie — Trofeo de Augusto',
    'frt.stop7': 'Èze — Pueblo medieval encaramado',
    'frt.book.h2': 'La Riviera os llama',
    'frt.book.script': 'Mónaco y más allá',
    'frt.book.lead': 'Reserve su French Riviera City Tour para una escapada inolvidable.',
    'nbn.eyebrow': 'Paseo nocturno · La magia de la noche',
    'nbn.script': 'Niza bajo las estrellas',
    'nbn.badge': '🌙 Noche · Niza iluminada',
    'nbn.desc1': 'La noche transforma Niza en un cuadro de luces. A bordo de su sidecar vintage, deslícese por la Promenade des Anglais iluminada y sienta el alma de la ciudad bajo las estrellas.',
    'nbn.desc2': 'Una experiencia sensorial única: el ronroneo del motor, la brisa marina de la noche, y la Costa Azul brillando a su alrededor. Un momento mágico que hay que vivir absolutamente.',
    'nbn.stop1': 'Promenade des Anglais iluminada',
    'nbn.stop2': 'Casco antiguo de noche',
    'nbn.stop3': 'Puerto de Niza y sus reflejos',
    'nbn.stop4': 'Miradores nocturnos secretos',
    'nbn.stop5': 'Panoramas y luces de la Riviera',
    'nbn.book.h2': 'La noche es vuestra',
    'nbn.book.script': 'Niza bajo las estrellas',
    'nbn.book.lead': 'Reserve su paseo nocturno para una experiencia extraordinaria.',
    'nbn.avail': 'Tardes bajo reserva',
    'float.book': 'Reservar',
  }
};

const flags = { fr: '🇫🇷', en: '🇬🇧', de: '🇩🇪', it: '🇮🇹', es: '🇪🇸' };
const flagUrls = {
  fr: 'https://flagcdn.com/w40/fr.png',
  en: 'https://flagcdn.com/w40/gb.png',
  de: 'https://flagcdn.com/w40/de.png',
  it: 'https://flagcdn.com/w40/it.png',
  es: 'https://flagcdn.com/w40/es.png'
};
const codes = { fr: 'FR', en: 'EN', de: 'DE', it: 'IT', es: 'ES' };
let currentLang = 'fr';

function setLanguage(lang) {
  if (!i18n[lang]) return;
  currentLang = lang;
  document.documentElement.lang = lang;

  // Plain text
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (i18n[lang][key] !== undefined) el.textContent = i18n[lang][key];
  });

  // HTML content
  document.querySelectorAll('[data-i18n-html]').forEach(el => {
    const key = el.getAttribute('data-i18n-html');
    if (i18n[lang][key] !== undefined) el.innerHTML = i18n[lang][key];
  });

  // Copyright with year
  const copyright = document.getElementById('copyright');
  if (copyright && i18n[lang]['footer.copyright']) {
    copyright.textContent = i18n[lang]['footer.copyright'].replace('{year}', new Date().getFullYear());
  }

  // Switcher UI
  // Update flag button
  const flagBtn = document.getElementById('langFlagBtn');
  if (flagBtn && flagUrls[lang]) {
    flagBtn.src = flagUrls[lang];
    flagBtn.alt = lang.toUpperCase();
  }
  document.querySelectorAll('.lang-option').forEach(btn => {
    btn.classList.toggle('active', btn.getAttribute('data-lang') === lang);
  });

  // Close dropdown
  document.getElementById('langSwitcher').classList.remove('open');

  // Save preference
  try { localStorage.setItem('rs-lang', lang); } catch(e) {}
}

// Lang switcher toggle
const langBtn = document.getElementById('langBtn');
const langSwitcher = document.getElementById('langSwitcher');

langBtn.addEventListener('click', e => {
  e.stopPropagation();
  langSwitcher.classList.toggle('open');
});

document.querySelectorAll('.lang-option').forEach(btn => {
  btn.addEventListener('click', e => {
    e.stopPropagation();
    setLanguage(btn.getAttribute('data-lang'));
  });
});

document.addEventListener('click', () => langSwitcher.classList.remove('open'));
langSwitcher.addEventListener('click', e => e.stopPropagation());

// ============================================================
// NAV SCROLL
// ============================================================
const nav = document.getElementById('nav');
const onScroll = () => {
  if (window.scrollY > 60) nav.classList.add('scrolled');
  else nav.classList.remove('scrolled');
};
window.addEventListener('scroll', onScroll, { passive: true });
onScroll();

// ============================================================
// MOBILE MENU
// ============================================================
const toggle = document.getElementById('navToggle');
const menu = document.getElementById('navMenu');
toggle.addEventListener('click', () => {
  toggle.classList.toggle('open');
  menu.classList.toggle('open');
});
menu.querySelectorAll('a').forEach(a => a.addEventListener('click', () => {
  if (menu.classList.contains('open')) {
    toggle.classList.remove('open');
    menu.classList.remove('open');
  }
}));

// ============================================================
// INIT
// ============================================================
// Init copyright in French
document.getElementById('copyright').textContent =
  i18n.fr['footer.copyright'].replace('{year}', new Date().getFullYear());

// ============================================================
// DÉTECTION AUTOMATIQUE DE LA LANGUE
// Priorité : 1) choix sauvegardé  2) IP géolocalisation  3) langue navigateur  4) français
// ============================================================

// Correspondance pays → langue (ISO 3166-1 alpha-2)
const countryToLang = {
  // Français
  FR:'fr', MC:'fr', BE:'fr', LU:'fr', CH:'fr',
  CI:'fr', SN:'fr', CM:'fr', ML:'fr', BF:'fr',
  MG:'fr', RW:'fr', TN:'fr', MA:'fr', DZ:'fr',
  GP:'fr', MQ:'fr', GF:'fr', RE:'fr', PM:'fr',
  // Anglais
  GB:'en', US:'en', CA:'en', AU:'en', NZ:'en',
  IE:'en', ZA:'en', IN:'en', NG:'en', GH:'en',
  SG:'en', HK:'en', MT:'en', JM:'en', TT:'en',
  // Italien
  IT:'it', SM:'it', VA:'it',
  // Allemand
  DE:'de', AT:'de', LI:'de',
  // Espagnol
  ES:'es', MX:'es', AR:'es', CO:'es', PE:'es',
  VE:'es', CL:'es', EC:'es', BO:'es', PY:'es',
  UY:'es', GT:'es', HN:'es', SV:'es', NI:'es',
  CR:'es', PA:'es', CU:'es', DO:'es', PR:'es',
};

async function detectAndSetLanguage() {
  // 1. Préférence déjà sauvegardée → respecter le choix de l'utilisateur
  try {
    const saved = localStorage.getItem('rs-lang');
    if (saved && i18n[saved]) { setLanguage(saved); return; }
  } catch(e) {}

  // 2. Détection par IP (timeout 3s pour ne pas bloquer le chargement)
  try {
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), 3000);
    const res = await fetch('https://ipapi.co/json/', { signal: controller.signal });
    clearTimeout(timer);
    if (res.ok) {
      const data = await res.json();
      const lang = countryToLang[data.country_code];
      if (lang && i18n[lang]) { setLanguage(lang); return; }
    }
  } catch(e) { /* Timeout ou erreur réseau → on continue */ }

  // 3. Langue du navigateur / système
  try {
    const codes = [navigator.language, ...(navigator.languages || [])];
    for (const code of codes) {
      const lang = (code || '').slice(0, 2).toLowerCase();
      if (i18n[lang]) { setLanguage(lang); return; }
    }
  } catch(e) {}

  // 4. Français par défaut
  setLanguage('fr');
}

detectAndSetLanguage();
